### PR TITLE
Add updated parser config

### PR DESCRIPTION
**Pull request by DiveFish**
`basic-parse.conf` doesn't seem to be up to date with the parser anymore. A second config has been added to account for this. Alternatively, `basic-parse.conf` could also be replaced by `extended-parse.conf`.

### CODE REVIEW

**Comment by danieldk** [comment]
Sorry, I missed this PR. I think the example configuration can just replace the existing one, rather than adding an additional configuration?

**Comment by danieldk** [comment]
Thanks. I rebased and squashed the commits. Will merge once Travis-CI is happy.

**Comment by DiveFish** [comment]
Thanks! Not sure what's wrong with my git that it doesn't

**Comment by DiveFish** [comment]
Thanks!
Sorry, accidentally hit the close button instead of just canceling a comment :-|

**Pull request merged**
